trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac
   
stages:
- stage: Stage1
  displayName: 'Create cert'
  jobs: 
  - job: CreateFile
    displayName: 'Create File'
    steps:
      - pwsh: |
          Get-Location
          Set-Content cert.pfx 'Real contents of pfx file here'
      - task: CopyFiles@2
        displayName: 'Copy Files'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '*.pfx'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish PFX file'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'deploy_pfx'
          publishLocation: 'pipeline'
        